# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: JABchem
description: A website for revision of Scottish SQA Exams in Chemistry, Maths, Physics and Biology at National 5, Higher and Advanced Higher. Included are SQA Past Papers, Marking Schemes, Traffic Light Evaluation Summaries, SQA Question Maps and so much more.  # this means to ignore newlines until "baseurl:"
author: Callum S
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://dev.jabchem.org.uk" # the base hostname & protocol for your site, e.g. http://example.com
reporturl: https://docs.google.com/forms/d/e/1FAIpQLSdLGt6lFgfMX3zQDPibfccYmPBzGqeKCtYNVdAU-7MXLaykNA/viewform?usp=pp_url&entry.1725158399=https://jabchem.org.uk
request: mailto:getintouch@jabchem.org.uk?subject=Permission
chemlogo: <i class="fa-solid fa-flask"></i>
mathlogo: <i class="fa-solid fa-calculator"></i>
physicslogo: <i class="fa-solid fa-atom"></i>
biologo: <i class="fa-solid fa-dna"></i>
chemcolour: c3e8ff
mathcolour: edc672
physicscolour: d7b5e8
biocolour: C2D8B2
# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  downloads:
    output: true
